import { ArrowLeft, BarChart3, Brain, CheckCircle2, Target, TrendingUp } from "lucide-react"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { ProjectImageFallback } from "@/components/project-image-fallback"

const technologies = ["Python", "LightGBM", "Bayesian Optimisation", "RFE", "Feature Engineering", "Credit Risk Modelling", "GCP", "BigQuery"]
const bullets = ["LightGBM core model with Recursive Feature Elimination to reduce a broad candidate set to a compact, high-performing subset.", "Bayesian Optimisation used to tune LightGBM hyperparameters, alongside new engineered features that delivered clear lift.", "Developed using 24 months of history with development and recent hold-out samples to test current portfolio performance.", "Score scaling fixed at 10:1 odds at 660, with 30 points doubling the odds."]

export default function KenyaScorecardPage() {
  return <div className="container mx-auto px-4 py-12"><div className="mb-8"><Link href="/projects"><Button variant="outline" size="sm"><ArrowLeft className="mr-2 h-4 w-4" /> Back to Projects</Button></Link></div><div className="max-w-6xl mx-auto">
    <header className="text-center mb-12"><div className="flex justify-center mb-4"><Target className="h-9 w-9 text-teal-600" /></div><h1 className="text-3xl md:text-5xl font-bold text-balance">Unifi Kenya Revised Behaviour Scorecard</h1><div className="flex flex-wrap justify-center gap-2 mt-5"><Badge className="bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200">Unifi Africa · Credit Risk / Data Science</Badge><Badge variant="outline">April 2026</Badge></div><p className="text-lg text-slate-600 dark:text-slate-400 max-w-3xl mx-auto mt-5">A rebuilt and productionised behavioural scorecard that predicts the probability a behaviour client reaches 3+ contractual delinquencies within six months after taking a subsequent loan.</p></header>
    <div className="relative h-[280px] md:h-[420px] rounded-lg overflow-hidden mb-12"><ProjectImageFallback src="/images/unifi_kenya.png" alt="Kenya behaviour scorecard analytics" fill className="object-cover" /></div>
    <div className="flex flex-wrap justify-center gap-2 mb-12">{technologies.map((tech) => <Badge key={tech} variant="secondary">{tech}</Badge>)}</div>
    <div className="grid md:grid-cols-2 gap-6 mb-8"><Card><CardContent className="p-7"><h2 className="text-2xl font-bold mb-5 flex items-center"><Brain className="mr-3 h-6 w-6 text-teal-600" />Modelling approach</h2><ul className="space-y-4">{bullets.map((item) => <li key={item} className="flex gap-3 text-slate-600 dark:text-slate-400 leading-relaxed"><CheckCircle2 className="h-5 w-5 text-teal-600 shrink-0 mt-0.5" />{item}</li>)}</ul></CardContent></Card><Card><CardContent className="p-7"><h2 className="text-2xl font-bold mb-5 flex items-center"><BarChart3 className="mr-3 h-6 w-6 text-teal-600" />Outcome</h2><div className="text-5xl font-bold text-teal-600 mb-2">0.62 → 0.67</div><p className="text-slate-600 dark:text-slate-400 mb-5">AUC improvement on the recent sample with stable risk ranking.</p><ul className="space-y-3 text-slate-600 dark:text-slate-400"><li>Approved by the Credit Committee.</li><li>Fully productionised and live in the credit decisioning flow.</li><li>Determines loan limits and amounts offered to clients.</li><li>Delivered the lowest 2@3 the Kenyan book has ever recorded.</li></ul></CardContent></Card></div>
    <Card className="mb-8"><CardContent className="p-7"><h2 className="text-2xl font-bold mb-4 flex items-center"><TrendingUp className="mr-3 h-6 w-6 text-teal-600" />Business impact</h2><p className="text-lg leading-relaxed text-slate-600 dark:text-slate-400">The scorecard translates behavioural repayment history into an actionable risk score used directly in client decisioning. By improving risk separation on recent data and maintaining stable ranking, it supports more precise lending limits while giving the Credit Committee a transparent, evidence-based basis for approval.</p></CardContent></Card>
    <div className="text-center"><Link href="/work/unifi-africa"><Button variant="outline">View Unifi Africa role</Button></Link></div>
  </div></div>
}
